# Generated by Django 6.0 on 2025-12-09 06:48

import storage_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='secret_name',
            field=models.CharField(default=storage_app.models.get_secret_name, max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
    ]
