# Generated by Django 6.0 on 2025-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_storage_secret_name_alter_storage_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
    ]
