# Generated by Django 6.0 on 2025-12-09 22:02

import django.core.files.storage
import storage_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_alter_storage_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='file',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location=storage_app.models.user_directory_path)),
        ),
    ]
