# Generated by Django 6.0 on 2025-12-19 07:53

import storage_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0004_alter_storage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='downloaded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='file',
            field=models.FileField(upload_to=storage_app.models.user_directory_path),
        ),
    ]
